In [87]:
from random import seed
from random import sample 
from random import randint
import numpy as np
import pandas as pd

seed(123)
from joblib import Parallel, delayed


In [98]:
n = 22
a = 2
b = 4

In [89]:
ns = randint(a, b)
ns

2

In [90]:
r = np.random.uniform(1, 0.2, ns)
r

array([0.38890766, 0.87898467])

In [91]:
rn = r/r.sum()
rn

array([0.13532849, 0.10507154, 0.05367359, 0.16072826, 0.11345146,
       0.08576837, 0.08939794, 0.08731246, 0.07516899, 0.09409891])

In [92]:
id = sample(range(n-1), ns)
id

[15, 1, 9, 10, 16, 20, 3, 13, 18, 17]

In [93]:
betas = np.repeat(.0, n, axis=0)
betas

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.])

In [94]:
for index, i in enumerate(id, start = 0):
    betas[i] = rn[index]

betas

array([0.        , 0.10507154, 0.        , 0.08939794, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.05367359,
       0.16072826, 0.        , 0.        , 0.08731246, 0.        ,
       0.13532849, 0.11345146, 0.09409891, 0.07516899, 0.        ,
       0.08576837, 0.        ])

In [91]:
# Read xlsx files
df = pd.read_excel('data/LM22Signature.xlsx', sheet_name = 0) 
X = df.iloc[:, 1:]

In [5]:
df.iloc[1]

Gene symbol                       ABCB9
B cells naive                   15.6035
B cells memory                  22.0948
Plasma cells                    653.392
T cells CD8                     24.2237
T cells CD4 naive               35.6715
T cells CD4 memory resting      30.0482
T cells CD4 memory activated    38.4554
T cells follicular helper       17.6048
T cells regulatory (Tregs)      46.0737
T cells gamma delta             19.7157
NK cells resting                21.8637
NK cells activated              16.3961
Monocytes                       20.3094
Macrophages M0                  56.2519
Macrophages M1                  29.3809
Macrophages M2                  40.3903
Dendritic cells resting         123.993
Dendritic cells activated       23.3846
Mast cells resting              53.4668
Mast cells activated            23.6157
Eosinophils                     29.7864
Neutrophils                     33.6791
Name: 1, dtype: object

In [97]:
A = np.dot(X, betas)

In [98]:
A

array([3.64495908e+01, 4.22783227e+01, 3.10001891e+02, 3.97910579e+01,
       4.57393984e+03, 2.75130638e+02, 1.38451303e+03, 9.91798876e+01,
       1.18249167e+03, 2.39467655e+03, 6.97628858e+02, 4.30762203e+02,
       6.07107536e+02, 8.94301884e+01, 2.12876501e+01, 2.03861609e+02,
       4.85648752e+02, 1.89871496e+03, 6.30441829e+02, 2.50583798e+01,
       8.02021157e+02, 4.03031405e+02, 1.09522926e+02, 7.36045327e+01,
       1.39981516e+02, 2.93931001e+02, 5.37562078e+02, 1.41070256e+01,
       1.93507322e+02, 3.52388704e+02, 1.07814375e+03, 3.31330425e+01,
       7.20313275e+02, 2.44658402e+03, 1.65069343e+02, 9.63461923e+01,
       2.71480501e+01, 6.90416007e+02, 1.44090207e+03, 3.70730252e+02,
       6.12919981e+02, 2.57255637e+02, 3.94107038e+02, 1.74548215e+01,
       1.78580963e+02, 2.36982874e+01, 1.50392977e+02, 1.16424620e+03,
       1.90771138e+03, 1.27222098e+03, 5.00673165e+01, 2.27420818e+01,
       3.85613555e+02, 3.27468867e+01, 4.78681691e+01, 4.40133852e+01,
      

In [237]:
seed(123)
def createBetas (X, a, b, n):
    ns = randint(a, b)
    r = np.random.uniform(1, 0.2, ns)
    rn = r/r.sum()
    id = sample(range(n), ns)
    betas = np.repeat(.0, n, axis=0)
    for index, i in enumerate(id, start = 0):
        betas[i] = rn[index]
        
    vector = X.to_numpy(copy=True)    
    vector = vector.flatten()
        
    A = np.dot(X, betas)
    AA = np.dot(X, betas) + vector[sample(range(len(vector)), len(X.index))].T
    
    return betas,id,A, AA

a = Parallel(n_jobs=4, backend='threading')(delayed(createBetas)(X = X, a = 2, b = 8, n = len(X.columns)) for i in range(1000))

In [253]:
pd.DataFrame(vector[sample(range(len(vector)), len(X.index))])

0
0     19.306564
1     60.015196
2     15.299851
3     54.330309
4    436.580027
..          ...
542    6.045929
543  292.520251
544   39.482714
545   89.489942
546   20.591084

[547 rows x 1 columns]

In [254]:
pd.DataFrame(vector[sample(range(len(vector)), len(X.index))].T)

0
0      5.639101
1      9.129397
2    288.716557
3     57.026752
4      6.391585
..          ...
542  162.104588
543   14.960164
544   29.605474
545    7.932019
546   26.914716

[547 rows x 1 columns]

In [240]:
vector[sample(range(len(vector)), len(X.index))]

array([2.82119942e+01, 4.01861952e+01, 5.58763643e+01, 6.62122662e+00,
       6.58236721e+01, 1.41298330e+01, 1.08104606e+01, 1.42161310e+03,
       4.74484624e+02, 6.43369387e+00, 1.47090652e+01, 3.27697347e+01,
       2.43660501e+02, 1.94516858e+01, 2.04958358e+02, 2.78343404e+02,
       6.41214213e+02, 8.13748044e+01, 1.43557394e+03, 4.90805175e+02,
       4.58307844e+01, 8.81553815e+01, 2.00476514e+01, 8.14171394e+01,
       1.00109354e+02, 7.56389405e+01, 8.49260779e+00, 3.97083555e+01,
       3.67149264e+02, 3.17791004e+02, 7.31568916e+03, 4.48709159e+02,
       4.15832575e+02, 2.41805251e+03, 2.49866115e+01, 4.51415936e+01,
       1.10108470e+03, 1.56968165e+02, 4.41420125e+02, 9.68358357e+01,
       1.72968293e+02, 2.11804747e+02, 3.56976687e+01, 1.36095620e+01,
       4.60878198e+02, 3.63900684e+01, 6.20213461e+02, 1.03486478e+02,
       1.56426098e+02, 2.39577985e+02, 2.70864199e+00, 1.47380875e+02,
       3.77773604e+01, 1.27346306e+03, 1.68895130e+02, 1.62813157e+02,
      

In [238]:
b = pd.DataFrame(a)
b

0  \
0    [0.0, 0.0, 0.6517065796118466, 0.0, 0.0, 0.0, ...   
1    [0.0, 0.13898433996753456, 0.0, 0.049382072387...   
2    [0.0, 0.0, 0.0, 0.0, 0.19410349819697006, 0.80...   
3    [0.0, 0.0, 0.0, 0.0, 0.0, 0.14626882648250547,...   
4    [0.17498761780341354, 0.0, 0.12753547940283402...   
..                                                 ...   
995  [0.0, 0.0, 0.0828576677154946, 0.0, 0.0, 0.0, ...   
996  [0.0, 0.0, 0.0, 0.0, 0.16318231285825788, 0.0,...   
997  [0.0, 0.06306092492191347, 0.0, 0.0, 0.2239753...   
998  [0.4997002073763539, 0.0, 0.0, 0.2545438404662...   
999  [0.12747488152004813, 0.09035734406425594, 0.0...   

                                  1  \
0                            [8, 2]   
1     [13, 8, 3, 1, 12, 10, 16, 21]   
2                            [5, 4]   
3                    [17, 10, 7, 5]   
4    [20, 17, 2, 0, 21, 19, 11, 16]   
..                              ...   
995           [2, 8, 11, 18, 7, 20]   
996        [9, 6, 18, 16, 7, 15, 4]   
997           [16, 21, 15, 6, 4, 1]   
998                   [3, 0, 10, 9]   
999         [8, 13, 1, 6, 5, 17, 0]   

                                                     2  \
0    [7.437324337689693, 441.8672306909248, 720.180...   
1    [23.559310430595982, 45.35942367168521, 656.67...   
2    [6.862839001942861, 31.13969749249658, 1090.62...   
3    [7.697763906305095, 22.511160375666805, 549.93...   
4    [112.85660879968599, 108.46770759701089, 280.6...   
..                                                 ...   
995  [6.939070860129339, 87.74142716513089, 875.443...   
996  [31.51640538237374, 46.38678052895154, 581.518...   
997  [43.96961384529849, 48.04484891562932, 610.088...   
998  [281.6284972177582, 19.079843655470388, 474.51...   
999  [77.48096440486903, 34.875609873892614, 585.90...   

                                                     3  
0    [106.57269282768969, 479.7158752009248, 1177.5...  
1    [53.607502860595986, 373.8104465716852, 3800.6...  
2    [271.46441530194284, 424.30538999249654, 1099....  
3    [270.5063414063051, 1539.3047233756668, 921.76...  
4    [114.90963894968598, 117.96570182501088, 322.5...  
..                                                 ...  
995  [107.75394056012934, 223.3339046651309, 1002.4...  
996  [4495.778538382374, 617.9040864289516, 1976.39...  
997  [56.707794655298486, 62.591485365629325, 640.7...  
998  [297.1574443577582, 61.66429593547039, 486.835...  
999  [573.902681004869, 257.1342425738926, 688.4051...  

[1000 rows x 4 columns]

In [203]:
(a[1][0] > 0).sum()

8

In [202]:
vector = [x[0] for x in a]
columns = ['V' + str(x+1) for x in range(len(a))]
betas = pd.DataFrame(np.column_stack(vector), columns=columns)

In [208]:
vector2 = [len(x[1]) for x in a]
ids = pd.DataFrame(np.column_stack(vector2))

In [112]:
ids

0    1    2    3    4    5    6    7    8    9    ...  990  991  992  993  \
0    2    8    2    3    6    2    5    7    5    4  ...    4    6    7    6   

   994  995  996  997  998  999  
0    7    3    4    3    6    7  

[1 rows x 1000 columns]

In [113]:
c = np.unique(ids.values)
np.sort(c)

array([2, 3, 4, 5, 6, 7, 8])

In [114]:
range(2,8)

range(2, 8)

In [204]:
estimate_lines = pd.DataFrame([(vector[i] > 0).sum() for i in range(1000)])

In [221]:
y = [estimate_lines[(ids.values == i)[0]][0] for index, i in enumerate(range(2,8), start = 0)]

In [223]:
for i in range(len(y)):
    print(y[i])
    print('-----------')

0      2
2      2
6      2
11     2
12     2
      ..
958    2
961    2
977    2
988    2
995    2
Name: 0, Length: 135, dtype: int64
-----------
10     3
17     3
21     3
27     3
30     3
      ..
966    3
980    3
982    3
983    3
997    3
Name: 0, Length: 152, dtype: int64
-----------
9      4
18     4
20     4
22     4
23     4
      ..
970    4
971    4
976    4
981    4
991    4
Name: 0, Length: 143, dtype: int64
-----------
3      5
8      5
13     5
16     5
34     5
      ..
985    5
989    5
994    5
998    5
999    5
Name: 0, Length: 141, dtype: int64
-----------
5      6
7      6
24     6
26     6
29     6
      ..
953    6
954    6
957    6
962    6
996    6
Name: 0, Length: 145, dtype: int64
-----------
4      7
33     7
37     7
40     7
60     7
      ..
959    7
963    7
978    7
987    7
990    7
Name: 0, Length: 127, dtype: int64
-----------


In [139]:
vector = [x[2] for x in a]
columns = ['V' + str(x+1) for x in range(len(a))]
Y = pd.DataFrame(np.column_stack(vector), columns=columns)
Y.insert(0, 'Gene symbol', df['Gene symbol'])

In [140]:
Y

Gene symbol           V1           V2           V3           V4  \
0         ABCB4     7.673002    89.153072    48.971419    93.913063   
1         ABCB9   252.944093    75.466101    23.491314    75.434049   
2         ACAP1   632.125573   343.625316   572.119823   246.438125   
3          ACHE    19.816211    23.481322    64.125618   148.818706   
4          ACP5  5631.592936  3511.926966  1441.301940  3766.244642   
..          ...          ...          ...          ...          ...   
542     ZNF204P    48.758206    57.061392    54.066110    53.431099   
543      ZNF222    32.720772    58.067209    77.998857    69.003645   
544     ZNF286A    70.880992   225.042651   282.213516   178.471875   
545      ZNF324    35.750297    30.012501    70.749312    53.038885   
546      ZNF442    32.183320    31.685693    46.017288    35.806223   

              V5           V6          V7           V8           V9  ...  \
0      62.088621    56.655501   10.574024    62.133919    24.254555  ...   
1      38.178484    65.054379  122.334218    85.719180    31.492915  ...   
2     419.885065   460.838182  276.133797   585.041419   705.762770  ...   
3     181.653186    39.208100  227.547769    33.310385    41.328040  ...   
4    2562.465631  3841.155449  908.523285  2159.867915  2344.835618  ...   
..           ...          ...         ...          ...          ...  ...   
542    55.479452    49.220967   67.020255    56.251190   108.192232  ...   
543    92.466949    76.298199   51.843388    83.130215   103.752530  ...   
544   144.134043   190.900156  127.154172   203.555087   108.444043  ...   
545    47.293548    48.953839   31.123677    34.999003   106.739263  ...   
546    40.883468    35.310897   56.534880    39.367911    28.900849  ...   

            V991         V992         V993         V994         V995  \
0      57.985336    36.365326    40.239448    25.707640     9.861928   
1      25.164367    79.622988    68.854989    92.933668    24.197179   
2     463.042073   627.771165   500.710117   270.525319   480.364715   
3     253.071079   222.404087   124.188930   168.821501    17.123620   
4    1794.585410  2229.277666  2394.477419  3805.807685  1571.106388   
..           ...          ...          ...          ...          ...   
542    73.162978    93.670140    76.274116    56.708595    76.239369   
543    60.934160    68.828740    81.915489    61.653266     9.285707   
544   230.512154   104.122230   138.287435   121.599219   288.928464   
545    74.532124    84.772633    57.069823    41.285583    24.443720   
546    45.608010    31.424052    36.480010    35.530474    18.941193   

            V996        V997        V998         V999        V1000  
0      76.025399  122.753714   14.723155   171.305793   119.547880  
1      37.472960   22.564546   47.198158    39.663271    28.433639  
2     402.688367  527.962128  328.634180   515.340929   463.864381  
3      31.154009  253.780944  116.804811    20.402001   197.548285  
4    3342.368717  542.849191  919.492011  2532.106841  1662.893678  
..           ...         ...         ...          ...          ...  
542    74.082308   91.209925   52.212540    53.140029    62.398021  
543    95.252363   44.246170  107.538203   104.596890    52.052568  
544   156.277020  251.969792  134.037765   259.911676   250.981308  
545    79.775995   31.598262   41.351515    39.350155    54.345457  
546    38.508023   32.533233   48.370295    27.523809    28.942266  

[547 rows x 1001 columns]